### ISSUE TITLE
Compat with Agricraft

### ISSUE THREAD

**Issue by kriNon** [quat1024/BotaniaTweaks#10]
Hey, so I know this isn't really the place to ask, (realistically it should be added on the agricraft side), but I was hoping you might be able to help out since from what I've been able to tell, agricraft doesn't seem to be under active development at the moment.

So, back in 1.7.10  agricraft implemented IHornHarvestable in [here](https://github.com/AgriCraft/AgriCraft/blob/1.7.10/src/main/java/com/InfinityRaider/AgriCraft/blocks/BlockCrop.java)
This made it so that crops could be harvested using botania's Horn of the Wild.

In 1.12.2 agricraft hasn't implemented this compatibility. I was thinking maybe it'd be possible to add the compatability from the botania's side.

Feel free to close the issue if it isn't within the scope of your mod.

Thanks!

**Comment by quat1024** [comment]
I could look in to that! It shouldn't be too hard to patch the interface on
to the Agricraft crop block.

**Comment by kriNon** [comment]
Awesome, it'd be much appreciated!

Off memory it used to harvest the crops and replant instead of just harvesting like it does with regular plants. Although you should be able to see how it was done in the class I linked you.

**Comment by quat1024** [comment]
^ Wow I'm good at Git

Anyway, this is implemented now, I just patched Agricraft to add the interface. When you use a Horn of the Wild, the crop drops as an item and resets its growth stage without removing the seed or crop sticks, just like if you had right clicked on it. I'll push this to Curse shortly.
