### ISSUE TITLE
You accidentally a hard dep on JEI

### ISSUE THREAD

**Issue by Hubry** [quat1024/BotaniaTweaks#16]
https://github.com/quat1024/BotaniaTweaks/blob/5ee48447d64a16854c0e11c9be265f08d72d9b25/src/main/java/quaternary/botaniatweaks/compat/jei/BotaniaTweaksJeiPlugin.java#L20-L21

This seems to try and classload your JEI plugin which crashes.

Yes, this is from that Tophat guy's crash on vazgoo's discord. Yes he tried to play modded minecraft without JEI.

Reuploaded his crash here https://gist.github.com/Hubry/2ff277c9f7d6259e8e3b7985642fdecc

**Comment by quat1024** [comment]
Thanks for the crash report :wink:
