### ISSUE TITLE
[Suggestion] Config to force enable botania bowl of water on non GoG maps

### ISSUE THREAD

**Issue by MrNinja93** [quat1024/BotaniaTweaks#19]
Same as the cheap orechid config option but one to enable filling a bowl with water like you can on GoG worlds.

**Comment by quat1024** [comment]
this is a cool idea!

**Comment by quat1024** [comment]
alright, implemented this (was surprisingly easy). Will be available in 1.5.1. Thanks for the suggestion!

**Comment by quat1024** [comment]
and it's on curse! have fun with it
