### ISSUE TITLE
Botania updated to 355

### ISSUE THREAD

**Issue by flamechair** [quat1024/BotaniaTweaks#25]
I noticed a message in the console regarding a possible incompatibility between using a version of botania tweaks built against a previous version of botania. If this is the case, can you update botania tweaks?

**Comment by quat1024** [comment]
Was hoping someone would notice that message ;)

Yep, I'm working on it - i'll leave this issue open until I finish it. Thanks for the reminder!

**Comment by quat1024** [comment]
Version 1.6.3 is approving on Curse right now, which I marked as compatible with Botania 356, and ported over some of the tiny potato display changes to the compressed tiny potatoes
