### ISSUE TITLE
[Suggestion] Better Rosa Arcana

### ISSUE THREAD

**Issue by lucidobservor** [quat1024/BotaniaTweaks#26]
The rosa arcana's current conversion rate of experience points to mana is pretty lackluster (35 via experience orb, 50 via player). In order to use the rosa arcana as a viable source of automated mana, the player would need a source of automated XP that far outstrips anything that adheres to vanilla balance. Adding an option to buff / configure this would fix that problem.

**Comment by quat1024** [comment]
implemented in 1.7 (now approving on the curseforges)

Wasn't sure the best number so I just made a multiplier you can set from 1 to 8.
