### ISSUE TITLE
[Suggestion] Config for cloak of balance recipe tweak

### ISSUE THREAD

**Issue by EmeraldsEmerald** [quat1024/BotaniaTweaks#27]
Hello.
The cloak of balance is a pretty neat (which is a mod by vazkii as well) botania bauble. However, the recipe deserves a bit of a tweak.

![image](https://user-images.githubusercontent.com/40524065/46371529-e84ccf80-c688-11e8-9bdd-67e93f1add82.png)
this is the current recipe. You can see the color, but the blocks are light gray wool.
I request an option to change the wool blocks into Clay blocks, because Clay is the single most balanced material.
It would even fit the cloak's colour!

Thank u very much

**Comment by quat1024** [comment]
No
