### ISSUE TITLE
Non-stacking items as agglomeration plate recipe inputs

### ISSUE THREAD

**Issue by noobanidus** [quat1024/BotaniaTweaks#38]
canItemStacksStack literally checks if they can stack. If you use input items which don't stack/only stack up to a maximum of one, it won't detect a recipe.

**Comment by quat1024** [comment]
doesn't actually seem to be the case

    public static boolean canItemStacksStack(@Nonnull ItemStack a, @Nonnull ItemStack b)
    {
        if (a.isEmpty() || !a.isItemEqual(b) || a.hasTagCompound() != b.hasTagCompound())
            return false;

        return (!a.hasTagCompound() || a.getTagCompound().equals(b.getTagCompound())) && a.areCapsCompatible(b);
    }

**Comment by quat1024** [comment]
oof
