### ISSUE TITLE
Turn off Extended Crafting compat.

### ISSUE THREAD

**Issue by Pival81** [quat1024/BotaniaTweaks#41]
I am using Extended Crafting only for the Ender Crafter, and I don't need all the crafty crates you add.
Is there a way to disable those? I haven't found a config for it.

**Comment by quat1024** [comment]
I used to have a config to (dis|en)able mod compatibility, but it ended up causing a lot of problems for testing.

Btweaks already has soft dependencies on _five_ other mods (avaritia, jei, extended crafting, dynamic trees, crafttweaker) and any combination of them might be present in a particular modpack. Being able to toggle off compat creates even *more* possibilities (there might be a bug that only appears when a mod is present but compat for it is turned off, for example)

That *saiiiid*, I didn't know Extended Crafting had a config option to turn off its tables :package: I'll try to only add the crates when Extended Crafting also adds its tables.

Thanks for reporting this, there are a lot of weird avenues with mod compatibility I haven't explored apparently...

**Comment by quat1024** [comment]
alright, hubry took care of this, should disable the crates when you just turn them off in ec's config. =

(they're still *registered* but cmon it's 3 block IDs, and not registering them causes more trouble tham it's worth imo)
