### ISSUE TITLE
JEI Only Shows Blocks With The Meta Of 0

### ISSUE THREAD

**Issue by TheLimePixel** [quat1024/BotaniaTweaks#43]
This is supposed to be Scorched Grass, which has a meta of 3, but instead if shows Dry Grass which has a meta of 0.
![image](https://user-images.githubusercontent.com/25333164/51389739-9348a280-1b2d-11e9-91d3-74e21fc1980d.png)

**Comment by Hubry** [comment]
https://github.com/quat1024/BotaniaTweaks/blob/0cf449f53f93263c1da0af91244a21926f21d160/src/main/java/quaternary/botaniatweaks/modules/shared/helper/MiscHelpers.java#L53

Basically no mod overrides that, only vanilla stuff, as Forge introduces a more sensitive version `getPickBlock`.

**Comment by quat1024** [comment]
Doesn't getpickblock need things like a world, position, raytraceresult

**Comment by Hubry** [comment]
Yeh but this just doesn't get overridden literally anywhere so our best bet is like trying the pickblock with nulls and resorting to getMetaFromState on exception, or something (or a fake world but please no).

**Comment by quat1024** [comment]
ok, this should be fixed in the next update thanks to hubry, thanks for reporting it!

![image](https://user-images.githubusercontent.com/2068021/51509068-e177d300-1dc5-11e9-87b8-cf9d372771fa.png)
