### ISSUE TITLE
[Suggestion] Configurable enchanting bonus for pylons (or option to remove enchantment bonus entirely)

### ISSUE THREAD

**Issue by Saereth** [quat1024/BotaniaTweaks#47]
As it is botania pylons by default are very powerful enchantment boosters, with mods that increase enchanting levels this quickly becomes problematic as you cant really gate the pylons too far as they are so integral to botania's core functionality. An option to alter how much they contribue to enchanting tables would be greatly appreciated if possibe.

**Comment by quat1024** [comment]
If you happen to have Apotheosis ive been told it has a configuration for this, so, yea

Still a good idea tho👀

**Comment by quat1024** [comment]
Ok I added a config option. You can configure each one individually or just set it to 0 to disable the enchantment effect entirely. The config goes up way above 15 but that's mainly if you have mods like apotheosis that add very bigly enchants.

Btw, I learned while making this that natura and gaia pylons have a better enchant power than the normal ones - they each count for 15, so just one of those pylons is a full bookshelf. That's pretty neat.
