### ISSUE TITLE
NoClassDefFoundError involving agglomeration recipes

### ISSUE THREAD

**Issue by misterplus** [quat1024/BotaniaTweaks#50]
java.lang.NoClassDefFoundError: com/blamejared/mtlib/helpers/InputHelper

I just don't know why, crafttweaker only showed this

**Comment by Hubry** [comment]
For now install [MTLib](https://www.curseforge.com/minecraft/mc-mods/mtlib), its a library used by some mods to make Crafttweaker integration easier - I thought quat moved away from it here but seems he still has one use left.

**Comment by misterplus** [comment]
Thanks a lot man, this took me an hour to find out, and there's no previous cases. 
I'd rather close this issue when there's a hard dependency on the mod itself.

**Comment by misterplus** [comment]
> For now install [MTLib](https://www.curseforge.com/minecraft/mc-mods/mtlib), its a library used by some mods to make Crafttweaker integration easier - I thought quat moved away from it here but seems he still has one use left.

Thanks a lot man, this nearly took me an hour to find out, but I'd rather keep this issue around until a hard dependency was added.

**Comment by quat1024** [comment]
Ah dammit, i will fix this when i get home. Thanks hubry for the diagnosis, I was sleeping x)

**Comment by quat1024** [comment]
Ok this should be fixed in version 1.8.6 which is approving on curse.
