### ISSUE TITLE
Galactic potato not being rainbow when placed

### ISSUE THREAD

**Issue by Mixu78** [quat1024/BotaniaTweaks#52]
Botania tweaks version 1.8.4, Minecraft 1.12.2

The galactic potato isn't rainbow when placed in-world, it is red and stays like that. When given to another potato to hold, it goes rainbow though

**Comment by quat1024** [comment]
What mods do you have on your client?

do you use anything like optifine, vanillafix, etc? Can you try without them ?

**Comment by quat1024** [comment]
Gonna call this one stale
