### ISSUE TITLE
Mild glitch with ProjectE

### ISSUE THREAD

**Issue by PaulUParadox** [quat1024/BotaniaTweaks#53]
When I made the Pure Daisy, i noticed that it had an EMC value. I went to my Transmutation Table to teach it the daisy, but instead it learned something called "Botania Flower (Miscellaneous Flower". The tool tip said that it came from the tweaks mod and that having one was a bug to be reported here.

**Comment by quat1024** [comment]
Sounds like a ProjectE issue
