### ISSUE TITLE
[Suggestion] Allow each generating flower to have a unique decay time

### ISSUE THREAD

**Issue by Goldenlion5648** [quat1024/BotaniaTweaks#56]
It would be cool if the endoflame could be set to only last for a few minutes, while something like the spectrolus could last hours.

**Comment by quat1024** [comment]
I agree that it would be cool, but I don't think it's very simple to implement. All of the flowers go through the same method in [SubTileGenerating](https://github.com/Vazkii/Botania/blob/1.12-final/src/main/java/vazkii/botania/api/subtile/SubTileGenerating.java#L109) for their decay time, and there's not really an easy way to tell which flower is calling the method.

I'll take a look, though, maybe I can make something work.

**Comment by quat1024** [comment]
Lol ok turns out, it's easy as fuck actually.

I'm not ready to push a new version just yet, but I'll try to get to it tomorrow, it will have this change in it. I redid the whole decay system.

**Comment by Goldenlion5648** [comment]
Wow thank you!

**Comment by quat1024** [comment]
*disappears for two weeks*

Wow ok, sorry for not posting the update sooner, should be available on curse now
