### ISSUE TITLE
Feature request: Lexicon agglomeration-recipe page-addition tweaker function

### ISSUE THREAD

**Issue by nihiltres** [quat1024/BotaniaTweaks#6]
Would you please add a tweaker function to add agglomeration recipe pages to the Lexica Botanica, like [the functions added by ModTweaker](http://crafttweaker.readthedocs.io/en/latest/#Mods/Modtweaker/Botania/Lexicon/)? I'd like to make sure all recipes are well-documented in my pack.

Thanks so much for the mod as-is!

**Comment by quat1024** [comment]
Implemented in https://github.com/quat1024/BotaniaTweaks/commit/14f6fe6507b30f4c6a34f8eb12f5b6dec728533b :D

Use it like this:
```
mods.botaniatweaks.AgglomerationPage.add("SomeUnlocalizedName", "botania.entry.someEntry", <an int page number>, <an AgglomerationRecipe object>);
```

The other format with the bajillion parameters can be used instead. I'll document it better on the wiki.

**Comment by quat1024** [comment]
They look like this, by the way:
![image](https://user-images.githubusercontent.com/2068021/40953499-f89591c2-684d-11e8-9b15-8957af9a2018.png)

If you add more ingredients, they arc around the multiblock in the center.

Right now it doesn't display the "multiblock replacements" if you use those, and the multiblock center is really obscured and can't be hovered over. I'll see what I can do
