### ISSUE TITLE
[Suggestion] Add ability to modify mana produced by each flower independently  

### ISSUE THREAD

**Issue by Goldenlion5648** [quat1024/BotaniaTweaks#60]
It would be useful to be able to modify the generation of the more difficult flowers such as the dandelifeon

**Comment by quat1024** [comment]
This is a balance line I don't want to touch, for a few reasons:

* Different flowers generate mana in different ways (code-wise) so I can't
write a single patch to blanket apply to all flowers.
* Some square is just gonna use it to make endoflames super OP.
* My previous attempts at rebalancing flowers were misguided and I regret
doing them.
