### ISSUE TITLE
Config typo

### ISSUE THREAD

**Issue by mathwiz617** [quat1024/BotaniaTweaks#9]
Line 7: # "**Forge** GoG": The Orechid will always be cheap to run, regardless of if Garden of Glass is loaded.

Should be: # "**Force** GoG": The Orechid will always be cheap to run, regardless of if Garden of Glass is loaded.

Emphasis mine.

EDIT: for that matter, "Force GoG" should be "Force_GoG". Same goes for "Force no GoG". Whitespace in configs is sometimes handled funny.

**Comment by quat1024** [comment]
oof

**Comment by quat1024** [comment]
Thanks for the report, fixed it. New values are `force_gog`, `force_no_gog`, and `default`.
